[project]
name = "paper-assistant"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.49.1",
    "openai>=2.5.0",
    "pypdf2>=3.0.1",
]
